apiVersion: v1
kind: Service
metadata:
  name: my-django-service
spec:
  type: NodePort
  ports:
    - port: 8000  # Puerto del servicio dentro del clúster
      targetPort: 8000  # Puerto del contenedor donde se ejecuta la aplicación
      nodePort: 30000  # Puerto accesible desde fuera del clúster
  selector:
    app: my-django-app  # Selector para apuntar a los pods de tu aplicación
